export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as Hero} from './Hero/Hero'
export {default as Mostpopular} from './Mostpopular/Mostpopular'
export {default as GamingLibrary} from './GamingLibrary/GamingLibrary'
